export let meshDiseaseCategories = [
  "Animal Diseases",
  "Bacterial Infections and Mycoses",
  "Cardiovascular Diseases",
  "Chemically-Induced Disorders",
  "Congenital, Hereditary, and Neonatal Diseases and Abnormalities",
  "Digestive System Diseases",
  "Disorders of Environmental Origin",
  "Endocrine System Diseases",
  "Eye Diseases",
  "Female Urogenital Diseases and Pregnancy Complications",
  "Hemic and Lymphatic Diseases",
  "Immune System Diseases",
  "Male Urogenital Diseases",
  "Musculoskeletal Diseases",
  "Neoplasms",
  "Nervous System Diseases",
  "Nutritional and Metabolic Diseases",
  "Occupational Diseases",
  "Otorhinolaryngologic Diseases",
  "Parasitic Diseases",
  "Pathological Conditions, Signs and Symptoms",
  "Respiratory Tract Diseases",
  "Skin and Connective Tissue Diseases",
  "Stomatognathic Diseases",
  "Virus Diseases",
  "Wounds and Injuries"
];

export let meshCatsAndSubcats = {
  "Animal Diseases": [
    "Animal Diseases",
    "Abortion, Veterinary +",
    "Actinobacillosis",
    "Aleutian Mink Disease",
    "Anal Gland Neoplasms",
    "Anaplasmosis",
    "Bird Diseases +",
    "Borna Disease",
    "Cat Diseases +",
    "Cattle Diseases +",
    "Digital Dermatitis",
    "Disease Models, Animal",
    "Dog Diseases +",
    "Enterotoxemia",
    "Erysipelothrix Infections +",
    "Fish Diseases +",
    "Foot-and-Mouth Disease",
    "Foot Rot",
    "Goat Diseases",
    "Heartwater Disease",
    "Hepatitis, Animal +",
    "Horse Diseases +",
    "Keratoconjunctivitis, Infectious",
    "Lameness, Animal",
    "Mammary Neoplasms, Animal",
    "Mink Viral Enteritis",
    "Muscular Dystrophy, Animal +",
    "Myxomatosis, Infectious",
    "Parasitic Diseases, Animal +",
    "Paratuberculosis",
    "Parturient Paresis",
    "Peste-des-Petits-Ruminants",
    "Pleuropneumonia, Contagious",
    "Primate Diseases +",
    "Pseudorabies",
    "Pythiosis",
    "Rinderpest",
    "Rodent Diseases +",
    "Salmonella Infections, Animal",
    "Sheep Diseases +",
    "Steatitis",
    "Swine Diseases +",
    "Venereal Tumors, Veterinary",
    "Vesicular Stomatitis",
    "Wasting Disease, Chronic",
    "Zoonoses"
  ],
  "Bacterial Infections and Mycoses": [
    "Bacterial Infections and Mycoses",
    "Bacterial Infections +",
    "Central Nervous System Infections +",
    "Infection +",
    "Mycoses +",
    "Zoonoses"
  ],
  "Cardiovascular Diseases": [
    "Cardiovascular Diseases",
    "Cardiovascular Abnormalities +",
    "Cardiovascular Infections +",
    "Heart Diseases +",
    "Pregnancy Complications, Cardiovascular +",
    "Vascular Diseases +"
  ],
  "Chemically-Induced Disorders": [
    "Chemically-Induced Disorders",
    "Drug-Related Side Effects and Adverse Reactions +",
    "Poisoning +",
    "Substance-Related Disorders +"
  ],
  "Congenital, Hereditary, and Neonatal Diseases and Abnormalities": [
    "Congenital, Hereditary, and Neonatal Diseases and Abnormalities",
    "Congenital Abnormalities +",
    "Fetal Diseases +",
    "Genetic Diseases, Inborn +",
    "Infant, Newborn, Diseases +"
  ],
  "Digestive System Diseases": [
    "Digestive System Diseases",
    "Biliary Tract Diseases +",
    "Digestive System Abnormalities +",
    "Digestive System Fistula +",
    "Digestive System Neoplasms +",
    "Gastrointestinal Diseases +",
    "Liver Diseases +",
    "Pancreatic Diseases +",
    "Peritoneal Diseases +"
  ],
  "Disorders of Environmental Origin": [
    "Disorders of Environmental Origin",
    "Environmental Illness +",
    "Preconception Injuries"
  ],
  "Endocrine System Diseases": [
    "Endocrine System Diseases",
    "Adrenal Gland Diseases +",
    "Bone Diseases, Endocrine",
    "Diabetes Mellitus +",
    "Dwarfism +",
    "Endocrine Gland Neoplasms +",
    "Female Athlete Triad Syndrome",
    "Gonadal Disorders +",
    "Parathyroid Diseases +",
    "Pituitary Diseases +",
    "Polyendocrinopathies, Autoimmune",
    "Thyroid Diseases +",
    "Tuberculosis, Endocrine"
  ],
  "Eye Diseases": [
    "Eye Diseases",
    "Asthenopia",
    "Cogan Syndrome",
    "Conjunctival Diseases +",
    "Corneal Diseases +",
    "Eye Abnormalities +",
    "Eye Diseases, Hereditary +",
    "Eye Hemorrhage +",
    "Eye Infections +",
    "Eye Injuries +",
    "Eye Manifestations +",
    "Eye Neoplasms +",
    "Eyelid Diseases +",
    "Lacrimal Apparatus Diseases +",
    "Lens Diseases +",
    "Ocular Hypertension +",
    "Ocular Hypotension",
    "Ocular Motility Disorders +",
    "Optic Nerve Diseases +",
    "Orbital Diseases +",
    "Pupil Disorders +",
    "Refractive Errors +",
    "Retinal Diseases +",
    "Scleral Diseases +",
    "Uveal Diseases +",
    "Vision Disorders +",
    "Vitreous Detachment"
  ],
  "Female Urogenital Diseases and Pregnancy Complications": [
    "Female Urogenital Diseases and Pregnancy Complications",
    "Female Urogenital Diseases +",
    "Pregnancy Complications +"
  ],
  "Hemic and Lymphatic Diseases": [
    "Hemic and Lymphatic Diseases",
    "Hematologic Diseases +",
    "Lymphatic Diseases +"
  ],
  "Immune System Diseases": [
    "Immune System Diseases",
    "Autoimmune Diseases +",
    "Erythroblastosis, Fetal +",
    "Glomerulonephritis, Membranoproliferative",
    "Graft vs Host Disease",
    "Hypersensitivity +",
    "Immune Reconstitution Inflammatory Syndrome",
    "Immunologic Deficiency Syndromes +",
    "Immunoproliferative Disorders +",
    "Purpura, Thrombocytopenic +",
    "Transfusion Reaction"
  ],
  "Male Urogenital Diseases": [
    "Male Urogenital Diseases",
    "Genital Diseases, Male +",
    "Pelvic Floor Disorders",
    "Tuberculosis, Urogenital +",
    "Urogenital Abnormalities +",
    "Urogenital Neoplasms +",
    "Urologic Diseases +"
  ],
  "Musculoskeletal Diseases": [
    "Musculoskeletal Diseases",
    "Bone Diseases +",
    "Cartilage Diseases +",
    "Fasciitis +",
    "Foot Deformities +",
    "Foot Diseases +",
    "Hand Deformities +",
    "Jaw Diseases +",
    "Joint Diseases +",
    "Muscular Diseases +",
    "Musculoskeletal Abnormalities +",
    "Rheumatic Diseases +"
  ],
  "Neoplasms": [
    "Neoplasms",
    "Cysts +",
    "Hamartoma +",
    "Neoplasms by Histologic Type +",
    "Neoplasms by Site +",
    "Neoplasms, Experimental +",
    "Neoplasms, Hormone-Dependent",
    "Neoplasms, Multiple Primary +",
    "Neoplasms, Post-Traumatic",
    "Neoplasms, Radiation-Induced +",
    "Neoplasms, Second Primary",
    "Neoplastic Processes +",
    "Neoplastic Syndromes, Hereditary +",
    "Paraneoplastic Syndromes +",
    "Precancerous Conditions +",
    "Pregnancy Complications, Neoplastic +"
  ],
  "Nervous System Diseases": [
    "Nervous System Diseases",
    "Autoimmune Diseases of the Nervous System +",
    "Autonomic Nervous System Diseases +",
    "Central Nervous System Diseases +",
    "Chronobiology Disorders +",
    "Cranial Nerve Diseases +",
    "Demyelinating Diseases +",
    "Nervous System Malformations +",
    "Nervous System Neoplasms +",
    "Neurocutaneous Syndromes +",
    "Neurodegenerative Diseases +",
    "Neurologic Manifestations +",
    "Neuromuscular Diseases +",
    "Neurotoxicity Syndromes +",
    "Restless Legs Syndrome",
    "Sleep Wake Disorders +",
    "Trauma, Nervous System +"
  ],
  "Nutritional and Metabolic Diseases": [
    "Nutritional and Metabolic Diseases",
    "Metabolic Diseases +",
    "Nutrition Disorders +"
  ],
  "Occupational Diseases": [
    "Occupational Diseases",
    "Agricultural Workers' Diseases +",
    "Asthma, Occupational",
    "Bird Fancier's Lung",
    "Burnout, Professional",
    "Dermatitis, Occupational",
    "Hand-Arm Vibration Syndrome",
    "High Pressure Neurological Syndrome",
    "Inert Gas Narcosis",
    "Laboratory Infection",
    "Persian Gulf Syndrome",
    "Pneumoconiosis +",
    "Sleep Disorders, Circadian Rhythm"
  ],
  "Otorhinolaryngologic Diseases": [
    "Otorhinolaryngologic Diseases",
    "Ciliary Motility Disorders +",
    "Ear Diseases +",
    "Laryngeal Diseases +",
    "Nose Diseases +",
    "Otorhinolaryngologic Neoplasms +",
    "Pharyngeal Diseases +"
  ],
  "Parasitic Diseases": [
    "Parasitic Diseases",
    "Central Nervous System Parasitic Infections +",
    "Coinfection",
    "Eye Infections, Parasitic +",
    "Helminthiasis +",
    "Intestinal Diseases, Parasitic +",
    "Liver Diseases, Parasitic +",
    "Lung Diseases, Parasitic +",
    "Mesomycetozoea Infections +",
    "Opportunistic Infections +",
    "Parasitemia",
    "Parasitic Diseases, Animal +",
    "Pregnancy Complications, Parasitic",
    "Protozoan Infections +",
    "Skin Diseases, Parasitic +",
    "Zoonoses +"
  ],
  "Pathological Conditions, Signs and Symptoms": [
    "Pathological Conditions, Signs and Symptoms",
    "Morphological and Microscopic Findings +",
    "Pathologic Processes +",
    "Pathological Conditions, Anatomical +",
    "Signs and Symptoms +"
  ],
  "Respiratory Tract Diseases": [
    "Respiratory Tract Diseases",
    "Bronchial Diseases +",
    "Ciliary Motility Disorders +",
    "Granuloma, Respiratory Tract +",
    "Laryngeal Diseases +",
    "Lung Diseases +",
    "Nose Diseases +",
    "Pleural Diseases +",
    "Respiration Disorders +",
    "Respiratory Hypersensitivity +",
    "Respiratory System Abnormalities +",
    "Respiratory Tract Fistula +",
    "Respiratory Tract Infections +",
    "Respiratory Tract Neoplasms +",
    "Thoracic Diseases +",
    "Tracheal Diseases +"
  ],
  "Skin and Connective Tissue Diseases": [
    "Skin and Connective Tissue Diseases",
    "Connective Tissue Diseases +",
    "Skin Diseases +"
  ],
  "Stomatognathic Diseases": [
    "Stomatognathic Diseases",
    "Ankyloglossia",
    "Jaw Diseases +",
    "Mouth Diseases +",
    "Pharyngeal Diseases +",
    "Stomatognathic System Abnormalities +",
    "Temporomandibular Joint Disorders +",
    "Tooth Diseases +"
  ],
  "Virus Diseases": [
    "Virus Diseases",
    "Arbovirus Infections +",
    "Bronchiolitis, Viral",
    "Central Nervous System Viral Diseases +",
    "Coinfection",
    "DNA Virus Infections +",
    "Encephalitis, Viral +",
    "Eye Infections, Viral +",
    "Fatigue Syndrome, Chronic",
    "Hepatitis, Viral, Animal +",
    "Hepatitis, Viral, Human +",
    "Opportunistic Infections +",
    "Pneumonia, Viral",
    "RNA Virus Infections +",
    "Sexually Transmitted Diseases +",
    "Skin Diseases, Viral +",
    "Slow Virus Diseases +",
    "Tumor Virus Infections +",
    "Viremia",
    "Zoonoses"
  ],
  "Wounds and Injuries": [
    "Wounds and Injuries",
    "Abdominal Injuries +",
    "Amputation, Traumatic",
    "Arm Injuries +",
    "Asphyxia",
    "Athletic Injuries",
    "Back Injuries +",
    "Barotrauma +",
    "Battered Child Syndrome",
    "Birth Injuries +",
    "Bites and Stings +",
    "Burns +",
    "Cold Injury +",
    "Contrecoup Injury",
    "Crush Injuries +",
    "Drowning +",
    "Electric Injuries +",
    "Esophageal Perforation",
    "Extravasation of Diagnostic and Therapeutic Materials",
    "Foreign Bodies +",
    "Fractures, Bone +",
    "Fractures, Cartilage",
    "Frostbite +",
    "Hand Injuries +",
    "Heat Stress Disorders +",
    "Hip Injuries +",
    "Joint Dislocations +",
    "Lacerations",
    "Leg Injuries +",
    "Microtrauma, Physical",
    "Multiple Trauma +",
    "Nasal Septal Perforation",
    "Neck Injuries +",
    "Occupational Injuries",
    "Radiation Injuries +",
    "Retropneumoperitoneum",
    "Rupture +",
    "Self Mutilation",
    "Shock, Traumatic +",
    "Shoulder Injuries +",
    "Soft Tissue Injuries +",
    "Spinal Cord Injuries +",
    "Sprains and Strains +",
    "Surgical Wound",
    "Tendon Injuries +",
    "Thoracic Injuries +",
    "Tooth Injuries +",
    "Trauma, Nervous System +",
    "Tympanic Membrane Perforation",
    "Vascular System Injuries",
    "War-Related Injuries",
    "Wounds, Nonpenetrating +",
    "Wounds, Penetrating +"
  ]
};
